### ISSUE TITLE
Can this toolkit be used under Windows?

### ISSUE THREAD

**Issue by SingyuTang** [tsutterley/gravity-toolkit#124]

**Comment by tsutterley** [comment]
Hypothetically, yes. We do include a Windows build as part of our continuous integration testing. This is using conda to build and install the toolkit. However, as I only work on *nix machines, it is largely untested for practical use on Windows.

**Comment by SingyuTang** [comment]
ok，thanks

**Comment by tsutterley** [comment]
I need to update the documentation for the new procedures and filter out any mention of Drive or WebDAV. But yes, PO.DAAC Drive is now deprecated. I don't believe you need to add any applications nor create WebDAV credentials anymore. `podaac_cumulus.py` uses your standard Earthdata credentials.

**Comment by SingyuTang** [comment]
Thank you for your answer
