### ISSUE TITLE
a crash when running import gravity_toolkit as gravtk

### ISSUE THREAD

**Issue by LuoLanhua** [tsutterley/gravity-toolkit#136]
Hello, why is there a crash when running import gravity_toolkit as gravtk, Process finished with exit code -1073741819 (0xC0000005)

**Comment by tsutterley** [comment]
Never seen that error. What's your Operating System and Python version?

**Comment by LuoLanhua** [comment]
Thank you for your reply, it is Windows system, Python3.7

**Comment by LuoLanhua** [comment]
I reinstalled this library in Python 3.9 and it ran smoothly

**Comment by tsutterley** [comment]
Okay, whew. I use *NIX machines so I would have had a hard time debugging this.
