### ISSUE TITLE
No Matching Geocenter Months

### ISSUE THREAD

**Issue by geodeepak** [tsutterley/gravity-toolkit#94]
where to change or reshape the input

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In [12], line 22
     20 end_mon = np.max(months)
     21 missing = sorted(set(np.arange(start_mon,end_mon+1)) - set(months))
---> 22 Ylms = gravtk.grace_input_months(widgets.base_directory, PROC, DREL, DSET,
     23     LMAX, start_mon, end_mon, missing, SLR_C20, DEG1, MMAX=MMAX,
     24     SLR_21=SLR_21, SLR_22=SLR_22, SLR_C30=SLR_C30, SLR_C40=SLR_C40,
     25     SLR_C50=SLR_C50, POLE_TIDE=POLE_TIDE, ATM=ATM)
     26 # create harmonics object and remove mean
     27 GRACE_Ylms = gravtk.harmonics().from_dict(Ylms)

File ~/Seasonal/read-GRACE-harmonics-main/notebooks/gravity_toolkit/grace_input_months.py:781, in grace_input_months(base_dir, PROC, DREL, DSET, LMAX, start_mon, end_mon, missing, SLR_C20, DEG1, **kwargs)
    779     if months_test:
    780         gm = ','.join(f'{gm:03d}' for gm in months_test)
--> 781         raise IOError(f'No Matching Geocenter Months ({gm})')
    782 # for each considered date
    783 for i,grace_month in enumerate(months):

OSError: No Matching Geocenter Months (248,249)

**Comment by tsutterley** [comment]
Hi @geodeepak, this error is pointing that you need an updated geocenter file (e.g. TN-13 from JPL) to cover the last two months of data. There are similar catches for using satellite laser ranging files to replace low degree and order harmonics. 

There is an option to the input to interpolate the existing geocenter file to cover these months (`MODEL_DEG1=True`), but I would exercise caution using this option for anything beyond creating quick-looks.
